# Generated by Django 5.2.5 on 2025-09-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_partnershipspage_portfoliopage_servicespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text="URL to the partner's logo image")),
                ('website_url', models.URLField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the brand's logo image"),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the product image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Which partner company owns this brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='business.partner'),
        ),
    ]
