# Generated by Django 5.2.5 on 2025-09-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path (e.g., /old-page/)', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='New URL path (e.g., /new-page/)', max_length=255)),
                ('redirect_type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', help_text='Type of redirect', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Is this redirect active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect Rule',
                'verbose_name_plural': 'Redirect Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sweet Bliss', help_text='Your website name', max_length=100)),
                ('default_meta_description', models.TextField(default='Sweet Bliss - Premium FMCG Distribution | Bringing Global Brands to Pakistan', help_text='Default meta description for pages without custom description', max_length=160)),
                ('company_name', models.CharField(default='Sweet Bliss', help_text='Official company name', max_length=100)),
                ('company_description', models.TextField(default='Premium FMCG Importer and Distributor - Connecting global brands with local markets across Pakistan', help_text='Company description for schema markup')),
                ('phone', models.CharField(blank=True, default='+92-315-7680420', help_text='Company phone number', max_length=20)),
                ('email', models.EmailField(blank=True, default='azan@sweetbliss.pk', help_text='Company email address', max_length=254)),
                ('address', models.TextField(blank=True, default='Lahore, Punjab, Pakistan', help_text='Company address')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID (e.g., G-XXXXXXXXXX)', max_length=20)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID (e.g., GTM-XXXXXXX)', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20)),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100)),
                ('bing_site_verification', models.CharField(blank=True, help_text='Bing Webmaster Tools verification code', max_length=100)),
                ('company_logo', models.ForeignKey(blank=True, help_text='Company logo for schema markup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('default_og_image', models.ForeignKey(blank=True, help_text='Default image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Global SEO Settings',
            },
        ),
    ]
